version: '3.9'

services:
  database:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    
    ports:
      - "5432:5432"
    
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - postgres_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"  

  backend:
    image: backend
    container_name: afeada-fastapi
    restart: always
    build:
      context: ./back
      dockerfile: Dockerfile
    command: gunicorn -c gunicorn.conf.py main:app
    env_file:
      - .env

    depends_on:
      - database

  nginx:
    depends_on:
      - backend
    build:
      context: ./nginx
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "80:80"

volumes:
  postgres_data:
    driver: local