"""empty message

Revision ID: 4b385b8d726c
Revises: 72f9a4da0458
Create Date: 2022-10-29 00:20:20.201660

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b385b8d726c'
down_revision = '72f9a4da0458'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_dancegroup_table_id', table_name='dancegroup_table')
    op.drop_table('dancegroup_table')
    op.drop_index('ix_affinity_table_id', table_name='affinity_table')
    op.drop_table('affinity_table')
    op.alter_column('deck_table', 'id_card',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('deck_table', 'id_user',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('events_table', 'id_autor',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('group_table', 'id_teacher',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('news_table', 'id_autor',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('time_table', 'id_group',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('time_table', 'id_event',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('user_table', 'id_address',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_table', 'id_address',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('time_table', 'id_event',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('time_table', 'id_group',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('news_table', 'id_autor',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('group_table', 'id_teacher',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('events_table', 'id_autor',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('deck_table', 'id_user',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('deck_table', 'id_card',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_table('affinity_table',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('id_relative', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id_child', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id_child'], ['user_table.id'], name='affinity_table_id_child_fkey'),
    sa.ForeignKeyConstraint(['id_relative'], ['user_table.id'], name='affinity_table_id_relative_fkey'),
    sa.PrimaryKeyConstraint('id', name='affinity_table_pkey')
    )
    op.create_index('ix_affinity_table_id', 'affinity_table', ['id'], unique=False)
    op.create_table('dancegroup_table',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('id_group', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id_user', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id_group'], ['group_table.id'], name='dancegroup_table_id_group_fkey'),
    sa.ForeignKeyConstraint(['id_user'], ['user_table.id'], name='dancegroup_table_id_user_fkey'),
    sa.PrimaryKeyConstraint('id', name='dancegroup_table_pkey')
    )
    op.create_index('ix_dancegroup_table_id', 'dancegroup_table', ['id'], unique=False)
    # ### end Alembic commands ###
