"""empty message

Revision ID: d2f094fa5898
Revises: 4b385b8d726c
Create Date: 2022-10-29 03:17:15.927160

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2f094fa5898'
down_revision = '4b385b8d726c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dancegroup_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_group', sa.Integer(), nullable=True),
    sa.Column('id_user', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_group'], ['group_table.id'], ),
    sa.ForeignKeyConstraint(['id_user'], ['user_table.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dancegroup_table_id'), 'dancegroup_table', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dancegroup_table_id'), table_name='dancegroup_table')
    op.drop_table('dancegroup_table')
    # ### end Alembic commands ###
