"""empty message

Revision ID: e2b2fa739812
Revises: 
Create Date: 2022-11-06 13:33:47.105715

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = 'e2b2fa739812'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cards_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('card_name', sa.String(length=32), nullable=False),
    sa.Column('card_discription', sa.String(length=512), nullable=False),
    sa.Column('card_look', sqlalchemy_utils.types.url.URLType(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cards_table_card_name'), 'cards_table', ['card_name'], unique=False)
    op.create_index(op.f('ix_cards_table_id'), 'cards_table', ['id'], unique=False)
    op.create_table('user_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('login', sa.String(length=64), nullable=False),
    sa.Column('password', sa.String(length=64), nullable=False),
    sa.Column('surename', sa.String(length=24), nullable=False),
    sa.Column('name', sa.String(length=24), nullable=False),
    sa.Column('patronymic', sa.String(length=24), nullable=True),
    sa.Column('avatar', sqlalchemy_utils.types.url.URLType(), nullable=True),
    sa.Column('phone', sa.String(length=12), nullable=True),
    sa.Column('dcp', sa.Integer(), nullable=True),
    sa.Column('role', sa.Enum('teacher', 'student', name='userrole'), nullable=True),
    sa.Column('qr_code', sqlalchemy_utils.types.url.URLType(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_table_created_at'), 'user_table', ['created_at'], unique=False)
    op.create_index(op.f('ix_user_table_id'), 'user_table', ['id'], unique=False)
    op.create_index(op.f('ix_user_table_login'), 'user_table', ['login'], unique=False)
    op.create_index(op.f('ix_user_table_password'), 'user_table', ['password'], unique=False)
    op.create_table('address_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('street', sa.String(length=128), nullable=False),
    sa.Column('house_number', sa.String(length=64), nullable=False),
    sa.Column('flat', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user_table.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_address_table_created_at'), 'address_table', ['created_at'], unique=False)
    op.create_index(op.f('ix_address_table_id'), 'address_table', ['id'], unique=False)
    op.create_table('characteristic_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('Strength', sa.Integer(), nullable=True),
    sa.Column('Agility', sa.Integer(), nullable=True),
    sa.Column('Flexibility', sa.Integer(), nullable=True),
    sa.Column('Stamina', sa.Integer(), nullable=True),
    sa.Column('Stress_resist', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user_table.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_characteristic_table_created_at'), 'characteristic_table', ['created_at'], unique=False)
    op.create_index(op.f('ix_characteristic_table_id'), 'characteristic_table', ['id'], unique=False)
    op.create_table('deck_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_card', sa.Integer(), nullable=True),
    sa.Column('id_user', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_card'], ['cards_table.id'], ),
    sa.ForeignKeyConstraint(['id_user'], ['user_table.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deck_table_id'), 'deck_table', ['id'], unique=False)
    op.create_table('events_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_title', sa.String(length=32), nullable=False),
    sa.Column('event_description', sa.String(length=512), nullable=True),
    sa.Column('event_date', sa.DateTime(), nullable=False),
    sa.Column('id_autor', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_autor'], ['user_table.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events_table_id'), 'events_table', ['id'], unique=False)
    op.create_table('group_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('id_teacher', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_teacher'], ['user_table.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_group_table_id'), 'group_table', ['id'], unique=False)
    op.create_table('news_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('news_title', sa.String(length=32), nullable=False),
    sa.Column('news_description', sa.String(length=512), nullable=True),
    sa.Column('photo', sqlalchemy_utils.types.url.URLType(), nullable=True),
    sa.Column('id_autor', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_autor'], ['user_table.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_news_table_id'), 'news_table', ['id'], unique=False)
    op.create_table('dancegroup_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_group', sa.Integer(), nullable=True),
    sa.Column('id_user', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_group'], ['group_table.id'], ),
    sa.ForeignKeyConstraint(['id_user'], ['user_table.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dancegroup_table_id'), 'dancegroup_table', ['id'], unique=False)
    op.create_table('time_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_group', sa.Integer(), nullable=True),
    sa.Column('id_event', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_event'], ['events_table.id'], ),
    sa.ForeignKeyConstraint(['id_group'], ['group_table.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_time_table_id'), 'time_table', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_time_table_id'), table_name='time_table')
    op.drop_table('time_table')
    op.drop_index(op.f('ix_dancegroup_table_id'), table_name='dancegroup_table')
    op.drop_table('dancegroup_table')
    op.drop_index(op.f('ix_news_table_id'), table_name='news_table')
    op.drop_table('news_table')
    op.drop_index(op.f('ix_group_table_id'), table_name='group_table')
    op.drop_table('group_table')
    op.drop_index(op.f('ix_events_table_id'), table_name='events_table')
    op.drop_table('events_table')
    op.drop_index(op.f('ix_deck_table_id'), table_name='deck_table')
    op.drop_table('deck_table')
    op.drop_index(op.f('ix_characteristic_table_id'), table_name='characteristic_table')
    op.drop_index(op.f('ix_characteristic_table_created_at'), table_name='characteristic_table')
    op.drop_table('characteristic_table')
    op.drop_index(op.f('ix_address_table_id'), table_name='address_table')
    op.drop_index(op.f('ix_address_table_created_at'), table_name='address_table')
    op.drop_table('address_table')
    op.drop_index(op.f('ix_user_table_password'), table_name='user_table')
    op.drop_index(op.f('ix_user_table_login'), table_name='user_table')
    op.drop_index(op.f('ix_user_table_id'), table_name='user_table')
    op.drop_index(op.f('ix_user_table_created_at'), table_name='user_table')
    op.drop_table('user_table')
    op.drop_index(op.f('ix_cards_table_id'), table_name='cards_table')
    op.drop_index(op.f('ix_cards_table_card_name'), table_name='cards_table')
    op.drop_table('cards_table')
    # ### end Alembic commands ###
